local.db.driver=com.mysql.cj.jdbc.Driver
local.db.url=jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
local.db.username=root
local.db.password=xhddlf336!

dev.db.driver=com.mysql.cj.jdbc.Driver
dev.db.url=jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
dev.db.username=joonsby
dev.db.password=xhddlf336!

prod.db.driver=com.mysql.cj.jdbc.Driver
prod.db.url=jdbc:mysql://localhost:3306/project?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
prod.db.username=joonsby
prod.db.password=xhddlf336!
